### ISSUE TITLE
Seperate repository

### ISSUE THREAD

**Issue by mojoaxel** [opensourcebeehives/BuzzBoard#1]
First! 🐝

I would recommend creating two repositories e.g. "BuzzBoard-Hardware" and "BuzzBoard-Firmware". I see the following benefits:
* The have different licenses. It makes sense to seperate the at a early stage to also seperate the licenses. At the moment is not really clear.
* Different Communities can develop: Firmware developers are maybe not so interested in changes in the hardware/and vise versa.
* The use of github tags and source-type-recognition would work better.

**Comment by pnaylor1982** [comment]
Done, new repos linked in README

**Comment by mojoaxel** [comment]
:clap: thx
