### ISSUE TITLE
Add board diagrams that work on Free Version of Eagle CAD

### ISSUE THREAD

**Issue by bennmapes** [opensourcebeehives/BuzzBoard#2]
When I try to open the schematic or board diagrams in Eagle I get the following error:

```
The free edition of EAGLE can't perform the requested action!

There are not enough sheets.
```

If possible could you export a version of the board that is flattened into two schematic sheets and no more than 2 signal or plane layers. Here is a reference to the available features of the free version https://www.autodesk.com/compare/eagle-vs-eagle-premium .

If not possible just close this issue.

**Comment by pnaylor1982** [comment]
Combined into one sheet
